const bcrypt = require("bcryptjs");
const mongoose = require("mongoose");

const playerNoteValueSchema = new mongoose.Schema(
  {
    note: { type: String, default: "" },
    updatedAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

const userSchema = new mongoose.Schema(
  {
    username: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      minlength: 3,
      maxlength: 50,
    },
    passwordHash: { type: String, required: true },
    drafts: [{ type: mongoose.Schema.Types.ObjectId, ref: "Draft" }],
    activeDraft: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Draft",
      default: null,
    },
    // GENERATED BY AI - Map of playerId to player note value
    playerNotes: { type: Map, of: playerNoteValueSchema, default: {} },
  },
  { timestamps: true, versionKey: false }
);

userSchema.methods.setPassword = async function setPassword(password) {
  this.passwordHash = await bcrypt.hash(password, 10);
};

userSchema.methods.verifyPassword = async function verifyPassword(password) {
  return bcrypt.compare(password, this.passwordHash);
};

const User = mongoose.model("User", userSchema);

module.exports = User;
