const API_BASE_URL = (
  import.meta.env.VITE_API_BASE_URL ||
  import.meta.env.VITE_BACKEND_URL ||
  "http://localhost:3000"
).replace(/\/+$/, "");

const CLIENT_BACKEND_URL = (
  import.meta.env.VITE_CLIENT_BACKEND_URL ||
  API_BASE_URL
).replace(/\/+$/, "");

const APP_CLIENT_KEY = import.meta.env.VITE_APP_CLIENT_KEY || "";

function getAuthHeaders() {
  if (!APP_CLIENT_KEY) {
    throw new Error("Missing VITE_APP_CLIENT_KEY in frontend .env");
  }

  return {
    Authorization: `Bearer ${APP_CLIENT_KEY}`,
  };
}

function getUserAuthHeaders() {
  const token = localStorage.getItem("authToken");
  if (!token) {
    return {};
  }
  return {
    Authorization: `Bearer ${token}`,
  };
}

/* GENERATED BY AI - request JSON */
async function requestJson(baseUrl, path, options = {}) {
  const {
    method = "GET",
    body,
    auth = true,
    userAuth = false,
    statusMessages = {},
  } = options;

  const headers = {
    ...(userAuth ? getUserAuthHeaders() : auth ? getAuthHeaders() : {}),
    ...(body ? { "Content-Type": "application/json" } : {}),
  };

  const res = await fetch(`${baseUrl}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!res.ok) {
    if (statusMessages[res.status]) throw new Error(statusMessages[res.status]);
    throw new Error(`Server error (${res.status})`);
  }

  return res.json();
}

export async function fetchPlayers() {
  return requestJson(API_BASE_URL, "/api/players", {
    statusMessages: {
      401: "Unauthorized — check your API key.",
    },
  });
}

export async function fetchPlayer(playerId) {
  return requestJson(API_BASE_URL, `/api/players/${encodeURIComponent(playerId)}`, {
    statusMessages: {
      401: "Unauthorized — check your API key.",
      404: "Player not found.",
    },
  });
}

export async function registerUser(username, password) {
  return requestJson(CLIENT_BACKEND_URL, "/api/users/register", {
    method: "POST",
    auth: false,
    body: { username, password },
    statusMessages: {
      409: "Username already exists.",
    },
  });
}

export async function login(username, password) {
  return requestJson(CLIENT_BACKEND_URL, "/api/users/login", {
    method: "POST",
    auth: false,
    body: { username, password },
    statusMessages: {
      404: "User not found.",
      401: "Invalid credentials.",
    },
  });
}

export async function verifyToken(token) {
  const res = await fetch(`${CLIENT_BACKEND_URL}/api/users/verify-token`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({}),
  });

  if (!res.ok) {
    throw new Error("Invalid or expired token.");
  }

  return res.json();
}

export async function saveUserPlayerNote(username, playerId, note) {
  return requestJson(CLIENT_BACKEND_URL, `/api/users/${encodeURIComponent(username)}/notes/${encodeURIComponent(playerId)}`, {
    method: "PUT",
    userAuth: true,
    body: { note },
  });
}

export async function fetchUserPlayerNote(username, playerId) {
  return requestJson(CLIENT_BACKEND_URL, `/api/users/${encodeURIComponent(username)}/notes/${encodeURIComponent(playerId)}`, {
    method: "GET",
    userAuth: true,
    statusMessages: {
      404: "User not found.",
    },
  });
}

export async function fetchAllUserNotes(username) {
  return requestJson(CLIENT_BACKEND_URL, `/api/users/${encodeURIComponent(username)}/notes`, {
    method: "GET",
    userAuth: true,
    statusMessages: {
      404: "User not found.",
    },
  });
}
