const API_BASE_URL = (
  import.meta.env.VITE_API_BASE_URL ||
  import.meta.env.VITE_BACKEND_URL ||
  "http://localhost:3000"
).replace(/\/+$/, "");

const CLIENT_BACKEND_URL = (
  import.meta.env.VITE_CLIENT_BACKEND_URL ||
  API_BASE_URL
).replace(/\/+$/, "");

const APP_CLIENT_KEY = import.meta.env.VITE_APP_CLIENT_KEY || "";

function getAuthHeaders() {
  if (!APP_CLIENT_KEY) {
    throw new Error("Missing VITE_APP_CLIENT_KEY in frontend .env");
  }

  return {
    Authorization: `Bearer ${APP_CLIENT_KEY}`,
  };
}

/* GENERATED BY AI - request JSON */
async function requestJson(baseUrl, path, options = {}) {
  const {
    method = "GET",
    body,
    auth = true,
    statusMessages = {},
  } = options;

  const headers = {
    ...(auth ? getAuthHeaders() : {}),
    ...(body ? { "Content-Type": "application/json" } : {}),
  };

  const res = await fetch(`${baseUrl}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!res.ok) {
    if (statusMessages[res.status]) throw new Error(statusMessages[res.status]);
    throw new Error(`Server error (${res.status})`);
  }

  return res.json();
}

export async function fetchPlayers() {
  return requestJson(API_BASE_URL, "/api/players", {
    statusMessages: {
      401: "Unauthorized — check your API key.",
    },
  });
}

export async function fetchPlayer(playerId) {
  return requestJson(API_BASE_URL, `/api/players/${encodeURIComponent(playerId)}`, {
    statusMessages: {
      401: "Unauthorized — check your API key.",
      404: "Player not found.",
    },
  });
}

export async function registerUser(username, password) {
  return requestJson(CLIENT_BACKEND_URL, "/api/users/register", {
    method: "POST",
    auth: false,
    body: { username, password },
    statusMessages: {
      409: "Username already exists.",
    },
  });
}

export async function saveUserPlayerNote(username, playerId, note) {
  return requestJson(CLIENT_BACKEND_URL, `/api/users/${encodeURIComponent(username)}/notes/${encodeURIComponent(playerId)}`, {
    method: "PUT",
    auth: false,
    body: { note },
  });
}
