const express = require("express");
const cors = require("cors");
const env = require("./config/env");
const { connectMongo } = require("./db/mongo");
const usersRoutes = require("./routes/users.routes");
const draftsRoutes = require("./routes/drafts.routes");
const teamsRoutes = require("./routes/teams.routes");

const app = express();

/* GENERATED BY AI - cors origin */
const allowedOrigins = env.corsOrigin
  .split(",")
  .map((origin) => origin.trim())
  .filter(Boolean);

const corsConfig = {
  origin: allowedOrigins.includes("*") ? "*" : allowedOrigins,
  methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  allowedHeaders: ["Content-Type", "Authorization"],
};

app.use(cors(corsConfig));
app.use(express.json());
app.use("/api/users", usersRoutes);
app.use("/api/drafts", draftsRoutes);
app.use("/api/teams", teamsRoutes);

app.use((err, _req, res, _next) => {
  console.error(err);
  res.status(500).json({ error: "Internal server error" });
});

async function start() {
  await connectMongo(env.mongodbUri);
  app.listen(env.port, () => {
    console.log(`Client backend listening on port ${env.port}`);
  });
}

module.exports = async (req, res) => {
  try {
    await connectMongo(env.mongodbUri);
    return app(req, res);
  } catch (error) {
    console.error("Failed to handle request:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
};

if (!process.env.VERCEL) {
  start().catch((error) => {
    console.error("Failed to start backend:", error);
    process.exit(1);
  });
}
