const express = require("express");
const jwt = require("jsonwebtoken");
const User = require("../models/user.model");
const Draft = require("../models/draft.model");
const authMiddleware = require("../middleware/auth");
const env = require("../config/env");

const router = express.Router();

// GENERATED BY AI - converts a Map of player notes into a plain JavaScript object so it can be returned in an API response.
function serializePlayerNotes(playerNotesMap) {
  return Object.fromEntries(playerNotesMap?.entries?.() || []);
}

router.post("/register", async (req, res, next) => {
  try {
    const { username, password } = req.body || {};

    if (!username || !password) {
      return res.status(400).json({ error: "username and password are required" });
    }

    const existing = await User.findOne({ username });
    if (existing) {
      return res.status(409).json({ error: "Username already exists" });
    }

    const user = new User({ username });
    await user.setPassword(password);
    await user.save();

    return res.status(201).json({
      username: user.username,
      drafts: user.drafts,
      activeDraft: user.activeDraft,
      playerNotes: serializePlayerNotes(user.playerNotes),
    });
  } catch (error) {
    return next(error);
  }
});

// Authenticates an existing user and returns a signed JWT token.
// This token is used by the frontend to access protected user routes.
router.post("/login", async (req, res, next) => {
  try {
    const { username, password } = req.body || {};

    if (!username || !password) {
      return res.status(400).json({ error: "username and password are required" });
    }

    const user = await User.findOne({ username });
    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }

    const isPasswordCorrect = await user.verifyPassword(password);
    if (!isPasswordCorrect) {
      return res.status(401).json({ error: "Invalid credentials" });
    }

    const token = jwt.sign(
      { id: user._id, username: user.username },
      env.jwtSecret,
      { expiresIn: env.jwtExpiry }
    );

    return res.status(200).json({
      message: "Login successful",
      token,
      user: {
        id: user._id,
        username: user.username,
        drafts: user.drafts,
        activeDraft: user.activeDraft,
      },
    });
  } catch (error) {
    return next(error);
  }
});

router.get("/:username/drafts", authMiddleware, async (req, res, next) => {
  try {
    const { username } = req.params;

    if (req.user.username !== username) {
      return res.status(403).json({ error: "Unauthorized" });
    }

    const user = await User.findOne({ username }).populate("drafts", "type numberOfTeams budgetPerTeam rosterSlots statCategories createdAt updatedAt");
    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }

    return res.json({
      username: user.username,
      drafts: user.drafts,
      activeDraft: user.activeDraft,
    });
  } catch (error) {
    return next(error);
  }
});

router.put("/:username/draft", authMiddleware, async (req, res, next) => {
  try {
    const { username } = req.params;
    const { draftId } = req.body || {};

    if (req.user.username !== username) {
      return res.status(403).json({ error: "Unauthorized" });
    }

    if (!draftId || typeof draftId !== "string" || draftId.trim() === "") {
      return res.status(400).json({ error: "draftId is required" });
    }

    const draftExists = await Draft.exists({ _id: draftId });
    if (!draftExists) {
      return res.status(404).json({ error: "Draft not found" });
    }

    const user = await User.findOne({ username });
    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }

    const ownsDraft = user.drafts.some((id) => id.equals?.(draftId) || id.toString() === draftId);
    if (!ownsDraft) {
      return res.status(403).json({ error: "Draft not associated with user" });
    }

    user.activeDraft = draftId;
    await user.save();

    return res.json({ username: user.username, activeDraft: user.activeDraft });
  } catch (error) {
    return next(error);
  }
});

router.post("/verify-token", async (req, res, next) => {
  const token = req.headers.authorization?.split(" ")[1];

  if (!token) {
    return res.status(401).json({ message: "Token missing or invalid" });
  }

  try {
    const decoded = jwt.verify(token, env.jwtSecret);
    const user = await User.findById(decoded.id).select("username drafts activeDraft");

    if (!user) {
      return res.status(401).json({ message: "Invalid or expired token" });
    }

    return res.status(200).json({ id: user._id, username: user.username, drafts: user.drafts, activeDraft: user.activeDraft });
  } catch (err) {
    return res.status(401).json({ message: "Invalid or expired token" });
  }
});

// Returns all saved scouting/player notes for the authenticated user.
// Used to hydrate the notes UI for the user's current draft workflow.
router.get("/:username/notes", authMiddleware, async (req, res, next) => {
  try {
    const { username } = req.params;

    if (req.user.username !== username) {
      return res.status(403).json({ error: "Unauthorized" });
    }

    const user = await User.findOne({ username });
    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }

    return res.json({
      username: user.username,
      playerNotes: serializePlayerNotes(user.playerNotes),
    });
  } catch (error) {
    return next(error);
  }
});

router.get("/:username/notes/:playerId", authMiddleware, async (req, res, next) => {
  try {
    const { username, playerId } = req.params;

    if (req.user.username !== username) {
      return res.status(403).json({ error: "Unauthorized" });
    }

    const user = await User.findOne({ username });
    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }

    const noteEntry = user.playerNotes.get(playerId);
    return res.json({
      username: user.username,
      playerId,
      note: noteEntry?.note || "",
      updatedAt: noteEntry?.updatedAt || null,
    });
  } catch (error) {
    return next(error);
  }
});

router.put("/:username/notes/:playerId", authMiddleware, async (req, res, next) => {
  try {
    const { username, playerId } = req.params;
    const { note } = req.body || {};

    if (req.user.username !== username) {
      return res.status(403).json({ error: "Unauthorized" });
    }

    if (typeof note !== "string") {
      return res.status(400).json({ error: "note must be a string" });
    }

    const user = await User.findOne({ username });
    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }

    user.playerNotes.set(playerId, { note, updatedAt: new Date() });

    await user.save();

    return res.json({
      username: user.username,
      playerNotes: serializePlayerNotes(user.playerNotes),
    });
  } catch (error) {
    return next(error);
  }
});

module.exports = router;
