import { useContext, useEffect, useState } from "react";
import { useParams, useNavigate, useSearchParams } from "react-router-dom";
import { fetchPlayer, fetchPlayerValuation, fetchUserPlayerNote, saveUserPlayerNote, fetchDraftById, postDraftPick } from "../services/api";
import { useAuth } from "../hooks/useAuth";
import { DraftContext } from "../context/DraftContext";
import { useToast } from "../context/ToastContext";
import "./PlayerPage.css";

/* GENERATED BY AI - stat labels */
const STAT_LABELS = {
  BA: "Batting Avg",
  HR: "Home Runs",
  RBI: "RBIs",
  SB: "Stolen Bases",
  H: "Hits",
  R: "Runs",
  BB: "Walks",
  SO: "Strikeouts",
  OBP: "On-Base %",
  SLG: "Slugging %",
  ERA: "ERA",
  W: "Wins",
  L: "Losses",
  K: "Strikeouts",
  IP: "Innings Pitched",
  WHIP: "WHIP",
};

function formatStat(key, value) {
  const floatStats = ["BA", "OBP", "SLG", "ERA", "WHIP"];
  if (floatStats.includes(key) && typeof value === "number") {
    return value.toFixed(3);
  }
  return String(value);
}

function Badge({ label, variant }) {
  return <span className={`badge badge-${variant}`}>{label}</span>;
}

function StatCard({ label, value }) {
  return (
    <div className="stat-card">
      <span className="stat-label">{label}</span>
      <span className="stat-value">{value}</span>
    </div>
  );
}

export default function PlayerPage() {
  const { playerId } = useParams();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [player, setPlayer] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [valuation, setValuation] = useState(null);
  const [notes, setNotes] = useState("");
  const [selectedTeam, setSelectedTeam] = useState("");
  const [draftPrice, setDraftPrice] = useState("");
  const [selectedPosition, setSelectedPosition] = useState("");
  const [nominatorTeam, setNominatorTeam] = useState("");
  const [saveMessage, setSaveMessage] = useState("");
  const [draftTeams, setDraftTeams] = useState([]);
  const [draftId, setDraftId] = useState(null);
  const [draft, setDraft] = useState(null);
  const [draftLoading, setDraftLoading] = useState(true);
  const { user } = useAuth();
  const { addPick, pickHistory } = useContext(DraftContext);
  const toast = useToast();

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    setPlayer(null);
    setValuation(null);

    fetchPlayer(playerId)
      .then((data) => {
        if (!cancelled) {
          setPlayer(data);
        }
      })
      .catch((err) => {
        if (!cancelled) setError(err.message);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [playerId]);

  useEffect(() => {
    let cancelled = false;

    async function loadValuation() {
      try {
        const data = await fetchPlayerValuation(playerId);
        if (!cancelled) {
          setValuation(data);
        }
      } catch {
        if (!cancelled) {
          setValuation(null);
        }
      }
    }

    loadValuation();
    return () => {
      cancelled = true;
    };
  }, [playerId, pickHistory.length]);

  // Fetch active draft and teams
  useEffect(() => {
    let cancelled = false;

    async function loadActiveDraft() {
      if (!user || !user.activeDraft) {
        setDraftLoading(false);
        setSaveMessage("No active draft found. Please select a draft first.");
        return;
      }

      try {
        const data = await fetchDraftById(user.activeDraft);
        if (!cancelled) {
          setDraftId(user.activeDraft);
          setDraft(data.draft || null);
          setDraftTeams(data.teams || []);
          setDraftLoading(false);
        }
      } catch (err) {
        if (!cancelled) {
          setSaveMessage(`Failed to load draft: ${err.message}`);
          setDraftLoading(false);
        }
      }
    }

    loadActiveDraft();

    return () => {
      cancelled = true;
    };
  }, [user?.activeDraft]);

  useEffect(() => {
    setNotes("");
    setSelectedTeam("");
    setDraftPrice("");
    setSelectedPosition("");
    setNominatorTeam("");
    setSaveMessage("");
  }, [playerId]);

  useEffect(() => {
    let cancelled = false;

    async function loadUserNote() {
      if (!user) {
        return;
      }

      try {
        const data = await fetchUserPlayerNote(user.username, playerId);
        if (!cancelled) {
          setNotes(data.note || "");
        }
      } catch (err) {
        if (!cancelled) {
          if (err.message === "User not found.") {
            setSaveMessage("User not found.");
          } else {
            setSaveMessage("Failed to load note from backend.");
          }
        }
      }
    }

    loadUserNote();

    return () => {
      cancelled = true;
    };
  }, [user?.username, playerId]);

  if (loading) {
    return (
      <div className="player-loading">
        <div className="spinner" />
        <p>Loading player data</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="player-error">
        <div className="error-icon">!</div>
        <h3>Failed to load player</h3>
        <p>{error}</p>
        <button className="retry-btn" onClick={() => navigate(0)}>
          Try Again
        </button>
      </div>
    );
  }

  if (!player) return null;

  const statEntries = player.stats ? Object.entries(player.stats) : [];
  const displayValue = Number.isFinite(valuation?.value) ? `$${valuation.value}` : null;

  async function saveNotes() {
    if (!user) {
      setSaveMessage("You must be logged in to save notes.");
      return;
    }

    try {
      await saveUserPlayerNote(user.username, playerId, notes);
      setSaveMessage("Notes saved to database.");
      setTimeout(() => setSaveMessage(""), 1500);
    } catch (err) {
      if (err.message === "User not found.") {
        setSaveMessage("User not found.");
        return;
      }
      setSaveMessage("Failed to save note to backend.");
    }
  }

  async function handleDraftPlayer() {
    if (!selectedTeam || !draftPrice || !selectedPosition || !nominatorTeam) {
      toast.warning("Please fill in all draft fields: team, price, position, and nominator.");
      return;
    }

    if (!draftId) {
      toast.error("No active draft found. Please select a draft first.");
      return;
    }

    // Already drafted check
    if (draftedPlayerIds.has(String(playerId))) {
      toast.error(`${player.name} has already been drafted.`);
      return;
    }

    const team = draftTeams.find((t) => t._id === selectedTeam);
    const price = parseFloat(draftPrice);

    if (!team) {
      toast.error("Selected team not found.");
      return;
    }

    if (team.budgetRemaining < price) {
      toast.error(
        `Budget exceeded — ${team.name} has $${team.budgetRemaining} remaining but needs $${price}.`
      );
      return;
    }

    if (!draft || !draft.rosterSlots) {
      toast.error("Draft roster configuration not found.");
      return;
    }

    const positionSlot = draft.rosterSlots.find((slot) => slot.position === selectedPosition);
    if (!positionSlot) {
      toast.error(`Position "${selectedPosition}" is not available in this draft's roster slots.`);
      return;
    }

    const playersInPosition = team.roster.filter((p) => p.position === selectedPosition).length;
    if (playersInPosition >= positionSlot.count) {
      toast.error(
        `No open ${selectedPosition} slots — ${team.name} has ${playersInPosition}/${positionSlot.count} filled.`
      );
      return;
    }

    try {
      const allConfiguredStats = [
        ...(draft?.statCategories?.hitters || []),
        ...(draft?.statCategories?.pitchers || []),
      ];
      const playerStats = {};
      if (player.stats && typeof player.stats === "object") {
        const lowerPlayerStats = Object.fromEntries(
          Object.entries(player.stats).map(([k, v]) => [k.toLowerCase(), v])
        );
        for (const key of allConfiguredStats) {
          const val = lowerPlayerStats[key.toLowerCase()];
          if (val !== undefined && val !== null && typeof val === "number") {
            playerStats[key] = val;
          }
        }
      }

      const pickData = {
        playerId,
        playerName: player.name,
        position: selectedPosition,
        price,
        teamId: selectedTeam,
        nominatorTeamId: nominatorTeam,
        stats: playerStats,
      };

      await postDraftPick(draftId, pickData);
      const nominator = draftTeams.find((t) => t._id === nominatorTeam);
      addPick({
        ...pickData,
        teamName: team.name,
        nominatorTeamName: nominator?.name,
        timestamp: new Date().toISOString(),
      });
      toast.success(`${player.name} drafted for $${price}!`);
      navigate("/app");
    } catch (err) {
      toast.error(`Failed to draft player: ${err.message}`);
    }
  }

  return (
    <div className="player-page">
      <button className="back-btn" onClick={() => navigate(-1)}>
        &larr; Back
      </button>

      <div className="player-layout-grid">
        <div className="player-left-column">
          <div className="player-header-card">
            <h2 className="player-name">{player.name}</h2>
            <div className="badge-row">
              {player.position?.map((pos) => (
                <Badge key={pos} label={pos} variant="position" />
              ))}
              {player.team && <Badge label={player.team} variant="team" />}
              {player.league && <Badge label={player.league} variant={player.league === "AL" ? "league-al" : "league-nl"} />}
            </div>
            {displayValue && <div className="player-valuation">Value: <strong>{displayValue}</strong></div>}

            <div className="stats-grid">
              {statEntries.map(([key, value]) => (
                <StatCard
                  key={key}
                  label={STAT_LABELS[key] || key}
                  value={formatStat(key, value)}
                />
              ))}
            </div>
          </div>

          <div className="player-notes-card">
            <h3>Player Notes</h3>
            <textarea
              className="player-notes-input"
              placeholder="Add notes about this player..."
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={4}
            />
            <button className="notes-save-btn" onClick={saveNotes}>
              Save Notes
            </button>
          </div>
        </div>

        <div className="player-actions-card">
          <h3>Draft Player</h3>
          <label className="form-label" htmlFor="team-select">
            Select Team
          </label>
          <select
            id="team-select"
            className="form-input"
            value={selectedTeam}
            onChange={(e) => setSelectedTeam(e.target.value)}
            disabled={draftTeams.length === 0}
          >
            <option value="">Choose team...</option>
            {draftTeams.map((team) => (
              <option key={team._id} value={team._id}>
                {team.name}
              </option>
            ))}
          </select>

          <label className="form-label" htmlFor="position-select">
            Position
          </label>
          <select
            id="position-select"
            className="form-input"
            value={selectedPosition}
            onChange={(e) => setSelectedPosition(e.target.value)}
            disabled={!player || !player.position || player.position.length === 0}
          >
            <option value="">Choose position...</option>
            {player && player.position && player.position.map((pos) => (
              <option key={pos} value={pos}>
                {pos}
              </option>
            ))}
          </select>

          <label className="form-label" htmlFor="nominator-select">
            Nominator Team
          </label>
          <select
            id="nominator-select"
            className="form-input"
            value={nominatorTeam}
            onChange={(e) => setNominatorTeam(e.target.value)}
            disabled={draftTeams.length === 0}
          >
            <option value="">Choose nominator...</option>
            {draftTeams.map((team) => (
              <option key={team._id} value={team._id}>
                {team.name}
              </option>
            ))}
          </select>

          <label className="form-label" htmlFor="draft-price">
            Draft Price
          </label>
          <input
            id="draft-price"
            className="form-input"
            type="number"
            min="1"
            placeholder="$"
            value={draftPrice}
            onChange={(e) => setDraftPrice(e.target.value)}
          />

          <button className="draft-btn" onClick={handleDraftPlayer} disabled={draftLoading || draftTeams.length === 0}>
            Draft Player
          </button>
        </div>
      </div>

      <div className="player-meta">
        <span className="meta-label">Last updated</span>
        <span className="meta-value">
          {new Date(player.fetchedAt).toLocaleString()}
        </span>
      </div>

      {saveMessage && <p className="player-feedback">{saveMessage}</p>}
    </div>
  );
}
