import { Routes, Route, Navigate } from "react-router-dom";
import Layout from "./components/Layout";
import PlayerPage from "./pages/PlayerPage";
import HomePage from "./pages/HomePage";
import DraftSetupPage from "./pages/DraftSetupPage";
import { LoginPage } from "./pages/LoginPage";
import { RegisterPage } from "./pages/RegisterPage";
import { AuthProvider } from "./context/AuthContext";
import { ProtectedRoute } from "./components/ProtectedRoute";

/* GENERATED BY AI */
export default function App() {
  return (
    <AuthProvider>
      <Routes>
        <Route path="/login" element={<LoginPage />} />
        <Route path="/register" element={<RegisterPage />} />
        <Route
          element={
            <ProtectedRoute>
              <Layout />
            </ProtectedRoute>
          }
        >
          <Route path="/" element={<HomePage />} />
          <Route path="/draft-setup" element={<DraftSetupPage />} />
          <Route path="/player/:playerId" element={<PlayerPage />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Route>
      </Routes>
    </AuthProvider>
  );
}
