import { Routes, Route, Navigate } from "react-router-dom";
import Layout from "./components/Layout";
import PlayerPage from "./pages/PlayerPage";
import HomePage from "./pages/HomePage";
import DraftSetupPage from "./pages/DraftSetupPage";
import DraftHistoryPage from "./pages/DraftHistoryPage";
import TeamPage from "./pages/TeamPage";
import ComparisonPage from "./pages/ComparisonPage";
import WelcomePage from "./pages/WelcomePage";
import { LoginPage } from "./pages/LoginPage";
import { RegisterPage } from "./pages/RegisterPage";
import { AuthProvider } from "./context/AuthContext";
import { DraftProvider } from "./context/DraftContext";
import { ToastProvider } from "./context/ToastContext";
import { ProtectedRoute } from "./components/ProtectedRoute";

/* GENERATED BY AI */
export default function App() {
  return (
    <AuthProvider>
      <ToastProvider>
      <DraftProvider>
      <Routes>
        <Route path="/" element={<WelcomePage />} />
        <Route path="/login" element={<LoginPage />} />
        <Route path="/register" element={<RegisterPage />} />
        <Route
          element={
            <ProtectedRoute>
              <Layout />
            </ProtectedRoute>
          }
        >
          <Route path="/app" element={<HomePage />} />
          <Route path="/draft-setup" element={<DraftSetupPage />} />
          <Route path="/draft-history" element={<DraftHistoryPage />} />
          <Route path="/compare" element={<ComparisonPage />} />
          <Route path="/team/:teamId" element={<TeamPage />} />
          <Route path="/player/:playerId" element={<PlayerPage />} />
          <Route path="*" element={<Navigate to="/app" replace />} />
        </Route>
      </Routes>
      </DraftProvider>
      </ToastProvider>
    </AuthProvider>
  );
}
