import { Routes, Route, Navigate } from "react-router-dom";
import Layout from "./components/Layout";
import PlayerPage from "./pages/PlayerPage";
import HomePage from "./pages/HomePage";

/* GENERATED BY AI */
export default function App() {
  return (
    <Routes>
      <Route element={<Layout />}>
        <Route path="/" element={<HomePage />} />
        <Route path="/player/:playerId" element={<PlayerPage />} />
        <Route path="*" element={<Navigate to="/" replace />} />
      </Route>
    </Routes>
  );
}
